#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    for i in range(1,len(arr)):
        if arr[i] < arr[i-1]:
            x = i 
            while x > 0 and arr[x] < arr[x-1]:
                temp = arr[x]
                arr[x] = arr[x-1] 
                print(" ".join(map(str, arr)))
                arr[x-1]=temp
                x-=1
    print(" ".join(map(str, arr)))
            
            
            

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
